---
title: "test"
author: "Allan"
date: '2023-06-20'
output:
  pdf_document: default
  html_document: default
---

```{r, echo = FALSE, message = FALSE, include=FALSE}
# load the required packages
packages <- c(
  "here", "knitr", # for the project's organization
  "readxl", "naniar","stringr", "janitor", # for wrangling
  "fpp3", "tsibbledata", # for time series
  "kableExtra", "skimr", "manipulate", "ggridges", "ggthemes", # for visualization
  "Rcpp", "sf", # for mapping
  "broom", "forecast" ,"caret"# modeling
)

purrr::walk(packages, library, character.only = TRUE) # load the packages

Sys.setenv(PATH = paste(Sys.getenv("PATH"), "C:/Rtools43/usr/bin", sep=";")) # setup Rtools43

# ggplot options
theme_set(theme_light())

# knitr options
opts_chunk$set(
  comment = "#>",
  collapse = TRUE,
  # cache = TRUE,
  fig.retina = 0.8, # figures are either vectors or 300 dpi diagrams
  dpi = 300,
  out.width = "70%",
  fig.align = "center",
  fig.width = 6,
  fig.asp = 0.618,
  fig.show = "hold",
  message = FALSE,
  echo = FALSE,
  warning = FALSE
)

# creating function for a nice kable
kable_maker <- function(a_tsibble, ...) {
  a_tsibble %>%
    kable(longtable = F, align='c', booktabs = T, ...) %>%
    kable_styling(bootstrap_options = c("striped", "hover"),
                  latex_options = c("hold_position", "scale_down"))
}

# using the kable_maker to display the first 5 rows for exercise 3
kable_head <- function(a_tsibble,...){
  a_tsibble %>% 
    head(5) %>% kable_maker(...)
}
```


```{r, echo = FALSE, message = FALSE, include=FALSE}
gadmCHE1 <- st_read("~/GitHub/Master-Thesis/Data/Switzerland/gadm36_CHE_shp/gadm36_CHE_1.shp") %>%
  separate(HASC_1, c('Pays', 'Canton')) %>%
  mutate(test = c(1:10, 30:35, 30:35, 50:53))
```

```{r, out.width = "100%"}
ggplot(gadmCHE1) +
  geom_sf(aes(fill = test)) +
  geom_sf_text(aes(label = Canton), size = 3.3, color = "black") +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.line = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.background = element_rect(fill = "white"),
        plot.background = element_rect(fill = "white"),
        axis.title = element_blank())
```


